services:
  db:
    image: postgres:16.9-alpine3.20
    restart: always

    ports:
      - '6543:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: muse_db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
